-- MySQL Script generated by MySQL Workbench
-- Sun Feb  6 22:47:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contactos` (
  `idcontacto` INT(11) NOT NULL,
  `telefono` INT(10) NULL DEFAULT NULL,
  `telcelular` INT(10) NOT NULL,
  PRIMARY KEY (`idcontacto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`contraseñas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contraseñas` (
  `idcontraseña` INT NOT NULL,
  `contraseñacol` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`idcontraseña`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalles` (
  `idcomentario` INT(11) NOT NULL,
  `comentariocol` VARCHAR(145) NULL DEFAULT NULL,
  PRIMARY KEY (`idcomentario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `idestado` INT(11) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horarios` (
  `id_horario` INT(11) NOT NULL,
  `hora` TIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_horario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menus` (
  `idmenu` INT(11) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `menucol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`roles_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles_usuario` (
  `idrol_usuario` INT(11) NOT NULL,
  `rol` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idrol_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `p_nombre` VARCHAR(10) NOT NULL,
  `s_nombre` VARCHAR(10) NULL DEFAULT NULL,
  `p_apellido` VARCHAR(10) NOT NULL,
  `s_apellido` VARCHAR(10) NULL DEFAULT NULL,
  `roles_usuario_idrol_usuario` INT(11) NOT NULL,
  `contactos_idcontacto` INT(11) NOT NULL,
  `contraseñas_idcontraseña` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_usuarios_roles_usuario1_idx` (`roles_usuario_idrol_usuario` ASC),
  INDEX `fk_usuarios_contactos1_idx` (`contactos_idcontacto` ASC),
  INDEX `fk_usuarios_contraseñas1_idx` (`contraseñas_idcontraseña` ASC),
  CONSTRAINT `fk_usuarios_roles_usuario1`
    FOREIGN KEY (`roles_usuario_idrol_usuario`)
    REFERENCES `mydb`.`roles_usuario` (`idrol_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_contactos1`
    FOREIGN KEY (`contactos_idcontacto`)
    REFERENCES `mydb`.`contactos` (`idcontacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_contraseñas1`
    FOREIGN KEY (`contraseñas_idcontraseña`)
    REFERENCES `mydb`.`contraseñas` (`idcontraseña`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`fechas_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fechas_reserva` (
  `id_fecha` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservas` (
  `idreserva` INT(11) NOT NULL,
  `cantpersonas` INT(2) NOT NULL,
  `estados_idestado` INT(11) NOT NULL,
  `horarios_idinfo` INT(11) NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  `fechas_reserva_id_fecha` INT NOT NULL,
  `detalles_idcomentario` INT(11) NOT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reservas_estados1_idx` (`estados_idestado` ASC),
  INDEX `fk_reservas_horarios1_idx` (`horarios_idinfo` ASC),
  INDEX `fk_reservas_usuarios1_idx` (`usuarios_id_usuario` ASC),
  INDEX `fk_reservas_fechas_reserva1_idx` (`fechas_reserva_id_fecha` ASC),
  INDEX `fk_reservas_detalles1_idx` (`detalles_idcomentario` ASC),
  CONSTRAINT `fk_reservas_estados1`
    FOREIGN KEY (`estados_idestado`)
    REFERENCES `mydb`.`estados` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_horarios1`
    FOREIGN KEY (`horarios_idinfo`)
    REFERENCES `mydb`.`horarios` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_fechas_reserva1`
    FOREIGN KEY (`fechas_reserva_id_fecha`)
    REFERENCES `mydb`.`fechas_reserva` (`id_fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_detalles1`
    FOREIGN KEY (`detalles_idcomentario`)
    REFERENCES `mydb`.`detalles` (`idcomentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios` (
  `idpaquete` INT(11) NOT NULL,
  `tipo_servicio` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idpaquete`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`menus_has_reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menus_has_reservas` (
  `menus_idmenu` INT(11) NOT NULL,
  `reservas_idreserva` INT(11) NOT NULL,
  PRIMARY KEY (`menus_idmenu`, `reservas_idreserva`),
  INDEX `fk_menus_has_reservas_reservas1_idx` (`reservas_idreserva` ASC),
  INDEX `fk_menus_has_reservas_menus1_idx` (`menus_idmenu` ASC),
  CONSTRAINT `fk_menus_has_reservas_menus1`
    FOREIGN KEY (`menus_idmenu`)
    REFERENCES `mydb`.`menus` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menus_has_reservas_reservas1`
    FOREIGN KEY (`reservas_idreserva`)
    REFERENCES `mydb`.`reservas` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`servicios_has_reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios_has_reservas` (
  `servicios_idpaquete` INT(11) NOT NULL,
  `reservas_idreserva` INT(11) NOT NULL,
  PRIMARY KEY (`servicios_idpaquete`, `reservas_idreserva`),
  INDEX `fk_servicios_has_reservas_reservas1_idx` (`reservas_idreserva` ASC) ,
  INDEX `fk_servicios_has_reservas_servicios1_idx` (`servicios_idpaquete` ASC) ,
  CONSTRAINT `fk_servicios_has_reservas_servicios1`
    FOREIGN KEY (`servicios_idpaquete`)
    REFERENCES `mydb`.`servicios` (`idpaquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicios_has_reservas_reservas1`
    FOREIGN KEY (`reservas_idreserva`)
    REFERENCES `mydb`.`reservas` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
