-- MySQL Script generated by MySQL Workbench
-- Sat Feb  5 10:17:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contacto` (
  `idcontacto` INT(11) NOT NULL,
  `telefono` INT(10) NULL DEFAULT NULL,
  `telcelular` INT(10) NOT NULL,
  PRIMARY KEY (`idcontacto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`contraseña`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contraseña` (
  `idcontraseña` INT NOT NULL,
  `contraseñacol` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`idcontraseña`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`especificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especificacion` (
  `idcomentario` INT(11) NOT NULL,
  `comentariocol` VARCHAR(145) NULL DEFAULT NULL,
  PRIMARY KEY (`idcomentario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `idestado` INT(11) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`info_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`info_reserva` (
  `idinfo` INT(11) NOT NULL,
  `hora` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idinfo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menu` (
  `idmenu` INT(11) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `menucol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`rol_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol_usuario` (
  `idrol_usuario` INT(11) NOT NULL,
  `rol` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idrol_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `p_nombre` VARCHAR(10) NOT NULL,
  `s_nombre` VARCHAR(10) NULL DEFAULT NULL,
  `p_apellido` VARCHAR(10) NOT NULL,
  `s_apellido` VARCHAR(10) NULL DEFAULT NULL,
  `contacto_idcontacto` INT(11) NOT NULL,
  `contraseña_idcontraseña` INT NOT NULL,
  `rol_usuario_idrol_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_usuario_contacto1_idx` (`contacto_idcontacto` ASC),
  INDEX `fk_usuario_contraseña1_idx` (`contraseña_idcontraseña` ASC),
  INDEX `fk_usuario_rol_usuario1_idx` (`rol_usuario_idrol_usuario` ASC),
  CONSTRAINT `fk_usuario_contacto1`
    FOREIGN KEY (`contacto_idcontacto`)
    REFERENCES `mydb`.`contacto` (`idcontacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_contraseña1`
    FOREIGN KEY (`contraseña_idcontraseña`)
    REFERENCES `mydb`.`contraseña` (`idcontraseña`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol_usuario1`
    FOREIGN KEY (`rol_usuario_idrol_usuario`)
    REFERENCES `mydb`.`rol_usuario` (`idrol_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `idreserva` INT(11) NOT NULL,
  `cantpersonas` INT(2) NOT NULL,
  `info_reserva_idinfo` INT(11) NOT NULL,
  `especificacion_idcomentario` INT(11) NOT NULL,
  `estado_idestado` INT(11) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reserva_info_reserva1_idx` (`info_reserva_idinfo` ASC) ,
  INDEX `fk_reserva_especificacion1_idx` (`especificacion_idcomentario` ASC) ,
  INDEX `fk_reserva_estado1_idx` (`estado_idestado` ASC) ,
  INDEX `fk_reserva_usuario1_idx` (`usuario_id` ASC) ,
  CONSTRAINT `fk_reserva_especificacion1`
    FOREIGN KEY (`especificacion_idcomentario`)
    REFERENCES `mydb`.`especificacion` (`idcomentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_estado1`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `mydb`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_info_reserva1`
    FOREIGN KEY (`info_reserva_idinfo`)
    REFERENCES `mydb`.`info_reserva` (`idinfo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`reserva_has_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva_has_menu` (
  `reserva_idreserva` INT(11) NOT NULL,
  `menu_idmenu` INT(11) NOT NULL,
  PRIMARY KEY (`reserva_idreserva`, `menu_idmenu`),
  INDEX `fk_reserva_has_menu_menu1_idx` (`menu_idmenu` ASC) ,
  INDEX `fk_reserva_has_menu_reserva1_idx` (`reserva_idreserva` ASC) ,
  CONSTRAINT `fk_reserva_has_menu_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `mydb`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_has_menu_reserva1`
    FOREIGN KEY (`reserva_idreserva`)
    REFERENCES `mydb`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicio` (
  `idpaquete` INT(11) NOT NULL,
  `tipo_servicio` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idpaquete`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`reserva_has_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva_has_servicio` (
  `reserva_idreserva` INT(11) NOT NULL,
  `servicio_idpaquete` INT(11) NOT NULL,
  PRIMARY KEY (`reserva_idreserva`, `servicio_idpaquete`),
  INDEX `fk_reserva_has_servicio_servicio1_idx` (`servicio_idpaquete` ASC) ,
  INDEX `fk_reserva_has_servicio_reserva1_idx` (`reserva_idreserva` ASC) ,
  CONSTRAINT `fk_reserva_has_servicio_reserva1`
    FOREIGN KEY (`reserva_idreserva`)
    REFERENCES `mydb`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_has_servicio_servicio1`
    FOREIGN KEY (`servicio_idpaquete`)
    REFERENCES `mydb`.`servicio` (`idpaquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
